[package]
name = "rslice"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.0"
actix-multipart = "0.7.2"
actix-web = "4.9.0"
futures = "0.3.31"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
stl_io = "0.8.5"
tempfile = "3.18.0"
